name: Deploy Azure Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  zip-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Archive /src to app.zip
      run: |
        cd src
        zip -r ../app.zip .
        cd ..
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Check and manage Storage Account network access
      run: |
        # Check current network access state
        current_access=$(az storage account show --name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
          --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
          --query "publicNetworkAccess" -o tsv)
        
        echo "Current public network access: $current_access"
        echo "network_was_disabled=false" >> $GITHUB_ENV
        
        if [ "$current_access" = "Disabled" ]; then
          echo "Enabling Azure Storage public access..."
          az storage account update --name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --public-network-access Enabled \
            --default-action Allow
          
          echo "network_was_disabled=true" >> $GITHUB_ENV
          
          # Wait for changes to propagate
          echo "Waiting for network changes to propagate..."
          sleep 30

        # Verify network rules
        az storage account show -n ${{ vars.AZURE_STORAGE_ACCOUNT }} --query networkRuleSet
        fi

    - name: Upload app.zip to Azure Storage
      run: |
        az storage blob upload -f 'app.zip' --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} -c ${{ vars.AZURE_STORAGE_CONTAINER }} -n 'app.zip' --overwrite true --auth-mode login

        url=$(az storage blob url -c ${{ vars.AZURE_STORAGE_CONTAINER }} -n 'app.zip' --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} --auth-mode login)
        echo "Blob URL: $url"
        echo "blob_url=$url" >> $GITHUB_ENV

    - name: Re-disable Azure Storage network access if it was initially denied
      if: env.network_was_disabled == 'true'
      run: |
        az storage account update --name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
          --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
          --public-network-access Disabled

    - name: Deploy to Azure Function
      run: |
        az functionapp config appsettings set --name ${{ vars.AZURE_FUNCTION_APP_NAME }} -g ${{ vars.AZURE_RESOURCE_GROUP }} \
          --settings WEBSITE_RUN_FROM_PACKAGE=${{ env.blob_url }} \
          AzureWebJobsStorage__blobServiceUri='https://${{ vars.AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net' \
          AzureWebJobsStorage__queueServiceUri='https://${{ vars.AZURE_STORAGE_ACCOUNT }}.queue.core.windows.net' \
          AzureWebJobsStorage__tableServiceUri='https://${{ vars.AZURE_STORAGE_ACCOUNT }}.table.core.windows.net' \
          WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID=${{ vars.WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID }}
        az functionapp restart --name ${{ vars.AZURE_FUNCTION_APP_NAME }} -g ${{ vars.AZURE_RESOURCE_GROUP }}